import { Project, Testimonial, BlogArticle, CareerJob, FAQ } from "./types";

export const PROJECT_LIST: Project[] = [
  {
    id: "mollik-tower",
    name: "Madina Tower",
    nameBn: "মদিনা টাওয়ার",
    location: "South Khan",
    locationBn: "দক্ষিণখান",
    type: "Residential",
    typeBn: "আবাসিক",
    size: "1450-3200 sqft",
    sizeBn: "১৪৫০-৩২০০ বর্গফুট",
    price: "৳85 Lac onwards",
    priceBn: "৳৮৫ লক্ষ থেকে শুরু",
    status: "Booking Open",
    statusBn: "বুকিং চলছে",
    image: "/uploads/0b856c28-6379-4010-a39d-76394ab88269.JPG",
    description: "Madina Tower is an exquisitely designed, south-facing project located at the prime block of Miyabari, Dakshinkhan. Presenting perfect ventilation, high architectural security, structural earthquake safety measures, and private elevator lobbies.",
    descriptionBn: "মদিনা টাওয়ার দক্ষিণখানের মিয়াবাড়ীর প্রধান ব্লকে অবস্থিত অত্যন্ত সূক্ষ্ম নকশায় তৈরি একটি দক্ষিণমুখী প্রজেক্ট। এতে রয়েছে পর্যাপ্ত আলো-বাতাস, সর্বোচ্চ নিরাপত্তা ব্যবস্থা, ভূমিকম্প প্রতিরোধী কাঠামো এবং চমৎকার লিফট লবি সুবিধা।",
    rajukApproved: true,
    earthquakeResistant: true,
    amenities: ["Infinity Pool", "Rooftop Observatory", "Private Gymnasium", "24/7 Multi-tier Security", "Dual Standby Generator", "Double Glazed low-E Windows"],
    amenitiesBn: ["ইনফিনিটি সুইমিং পুল", "ছাদভিত্তিক পর্যবেক্ষণ কেন্দ্র", "ব্যক্তিগত জিমনেসিয়াম", "২৪/৭ বহুতর নিরাপত্তা", "দ্বৈত ব্যাকআপ জেনারেটর", "ডাবল গ্লেজড গ্লাস উইন্ডো"],
    specs: [
      { label: "Land Area", labelBn: "জমির পরিমাণ", value: "12 Katha", valueBn: "১২ কাঠা" },
      { label: "Building Height", labelBn: "ভবনের উচ্চতা", value: "G + 14 Floors", valueBn: "জি + ১৪ তলা" },
      { label: "Total Apartments", labelBn: "মোট অ্যাপার্টমেন্ট", value: "28 Premium Units", valueBn: "২৮টি প্রিমিয়াম ইউনিট" },
      { label: "Car Parking", labelBn: "গাড়ি পার্কিং", value: "Ample Basement Slots", valueBn: "প্রশস্ত বেসমেন্ট স্লট" }
    ],
    dwgUrl: "/uploads/Mollik P-1.dwg",
    dwgFilename: "Mollik P-1.dwg",
    pdfUrl: "/uploads/প্রোজেক্ট ১-gathuni.pdf",
    pdfFilename: "প্রোজেক্ট ১-gathuni.pdf"
  },
  {
    id: "mollik-heights",
    name: "Bismillah Tower",
    nameBn: "বিসমিল্লাহ্ টাওয়ার",
    location: "South Khan",
    locationBn: "দক্ষিণখান",
    type: "Residential",
    typeBn: "আবাসিক",
    size: "1200-2800 sqft",
    sizeBn: "১২০০-২৮০০ বর্গফুট",
    price: "৳72 Lac onwards",
    priceBn: "৳৭২ লক্ষ থেকে শুরু",
    status: "Few Units Left",
    statusBn: "সীমিত ইউনিট বাকি",
    image: "/uploads/4ba54971-0a0f-4b98-b36b-3a68b5dbcd3a.JPG",
    description: "Designed with modern state-of-the-art layout requirements, Bismillah Tower provides dynamic lifestyle spaces in Dakshinkhan, Miyabari. Enjoy quick transit to Uttara hubs while preserving a completely quiet residential sanctuary.",
    descriptionBn: "আধুনিক আবাসন চাহিদার সাথে মিল রেখে ডিজাইন করা বিসমিল্লাহ্ টাওয়ার দক্ষিণখানের মিয়াবাড়ীতে চমৎকার এক প্রশান্তিময় আবাসনের প্রতিশ্রুতি দেয়। উত্তরার কাছাকাছি যোগাযোগ সুবিধা এবং শান্ত পরিবেশের একটি মনোরম মেলবন্ধন।",
    rajukApproved: true,
    earthquakeResistant: true,
    amenities: ["Rooftop Cafe Area", "Grand Reception Lobby", "Indoor Kids Play Zone", "Fully Automated Lifts", "Underground Rainwater Harvesting", "Fiber Optic Connectivity"],
    amenitiesBn: ["রফটপ ক্যাফে এরিয়া", "বিশাল অভ্যর্থনা লবি", "ইনডোর শিশু বিনোদন কেন্দ্র", "সম্পূর্ণ অটোমেটিক লিফট", "ভূগর্ভস্থ বৃষ্টির পানি সংরক্ষণ", "ফাইবার অপটিক ইন্টারনেট সংযোগ"],
    specs: [
      { label: "Land Area", labelBn: "জমির পরিমাণ", value: "10 Katha", valueBn: "১০ কাঠা" },
      { label: "Building Height", labelBn: "ভবনের উচ্চতা", value: "G + 12 Floors", valueBn: "জি + ১২ তলা" },
      { label: "Total Apartments", labelBn: "মোট অ্যাপার্টমেন্ট", value: "24 Premium Units", valueBn: "২৪টি প্রিমিয়াম ইউনিট" },
      { label: "Car Parking", labelBn: "গাড়ি পার্কিং", value: "2 Bays Per Apartment", valueBn: "প্রতি ফ্ল্যাটে ২টি পার্কিং" }
    ],
    dwgUrl: "/uploads/prpject2 floor plan.dwg",
    dwgFilename: "prpject2 floor plan.dwg",
    pdfUrl: "/BISMILLAH TOWER - 02.pdf",
    pdfFilename: "BISMILLAH TOWER - 02.pdf"
  },
  {
    id: "mollik-garden",
    name: "Apon Bhubon",
    nameBn: "আপন ভুবন",
    location: "South Khan",
    locationBn: "দক্ষিণখান",
    type: "Residential",
    typeBn: "আবাসিক",
    size: "1600-3500 sqft",
    sizeBn: "১৬০০-৩৫০০ বর্গফুট",
    price: "৳95 Lac onwards",
    priceBn: "৳৯৫ লক্ষ থেকে শুরু",
    status: "New Launch",
    statusBn: "নতুন লঞ্চ",
    image: "/uploads/6c08c96c-3d6b-436a-a3fe-54f2b07c0df4.JPG",
    description: "Apon Bhubon represents natural eco-friendly architecture with green landscaping in Dakshinkhan, Miyabari. Highly secure, BNBC structural code compliant, featuring modern common areas and automated backup services.",
    descriptionBn: "আপন ভুবন দক্ষিণখানের মিয়াবাড়ীতে সবুজ ও পরিবেশবান্ধব স্থাপত্যের এক অনন্য সৃষ্টি। বিএনবিসি কোড অনুযায়ী ভূমিকম্প সহনশীল করে নির্মিত চমৎকার এই প্রজেক্টে রয়েছে আধুনিক নাগরিক সুবিধার সব আয়োজন।",
    rajukApproved: true,
    earthquakeResistant: true,
    amenities: ["Solar-powered Common Areas", "Jogging Track", "Community Meeting Suite", "Aroma Herb Garden", "High-capacity Cargo Elevator", "Water Filtration Osmosis System"],
    amenitiesBn: ["সৌরশক্তি চালিত কমন স্পেস", "জগিং ট্র্যাক", "কমিউনিটি ডিসকাশন হল", "অ্যারোমা হার্বাল গার্ডেন", "উচ্চ ক্ষমতাসম্পন্ন কার্গো লিফট", "ওয়াটার ফিল্টারিং সিস্টেম"],
    specs: [
      { label: "Land Area", labelBn: "জমির পরিমাণ", value: "15 Katha", valueBn: "১৫ কাঠা" },
      { label: "Building Height", labelBn: "ভবনের উচ্চতা", value: "G + 10 Floors", valueBn: "জি + ১০ তলা" },
      { label: "Total Apartments", labelBn: "মোট অ্যাপার্টমেন্ট", value: "20 Spacious Homes", valueBn: "২০টি আরামদায়ক অ্যাপার্টমেন্ট" },
      { label: "Car Parking", labelBn: "গাড়ি পার্কিং", value: "Secured Ground Parking", valueBn: "সুরক্ষিত গ্রাউন্ড পার্কিং" }
    ],
    dwgUrl: "/uploads/প্রোজেক্ট ৩.dwg",
    dwgFilename: "প্রোজেক্ট ৩.dwg",
    pdfUrl: "/uploads/p3 floor plan.pdf",
    pdfFilename: "p3 floor plan.pdf"
  },
  {
    id: "mollik-serenade",
    name: "Mollik City Tower",
    nameBn: "মল্লিক সিটি টাওয়ার",
    location: "South Khan",
    locationBn: "দক্ষিণখান",
    type: "Penthouse",
    typeBn: "পেন্টহাউস / ডুপ্লেক্স",
    size: "1800-3000 sqft",
    sizeBn: "১৮০০-৩০০০ বর্গফুট",
    price: "৳1.2 Crore onwards",
    priceBn: "৳১.২ কোটি থেকে শুরু",
    status: "Ongoing",
    statusBn: "চলমান প্রকল্প",
    image: "/uploads/55e673fc-7278-4f95-9959-6d8c2c83543a.JPG",
    description: "Located prominently in the rapidly developing area of Uttarkhan, Mollik City Tower features exquisite hand-carved finishing, spacious dining rooms, and high quality security features suited for premier living.",
    descriptionBn: "উত্তরখানের ক্রমবর্ধমান উন্নত এলাকায় চমৎকার অবস্থানে নির্মিত মল্লিক সিটি টাওয়ার। দৃষ্টিনন্দন ডিজাইন ও মজবুত কাঠামোর সাথে প্রস্তুত এই প্রজেক্টে রয়েছে প্রিমিয়াম ফিটিংস এবং সর্বোচ্চ নিরাপত্তা ব্যবস্থা।",
    rajukApproved: true,
    earthquakeResistant: true,
    amenities: ["Private Plunge Pools", "Rooftop BBQ terrace", "Soundproof Acoustic Glazing", "24-Hour Advanced CCTV", "Centralized Gas piping and safety valves"],
    amenitiesBn: ["ব্যক্তিগত মিনি সুইমিং পুল", "রফটপ বারবিকিউ টেরেস", "শব্দ নিরোধক অ্যাকোস্টিক গ্লেজিং", "২৪ ঘণ্টা সিসিটিভি পাহারা", "সেন্ট্রাল গ্যাস ও ফায়ার সেফটি ভালভ"],
    specs: [
      { label: "Land Area", labelBn: "জমির পরিমাণ", value: "8 Katha", valueBn: "৮ কাঠা" },
      { label: "Building Height", labelBn: "ভবনের উচ্চতা", value: "G + 9 Floors", valueBn: "জি + ৯ তলা" },
      { label: "Total Apartments", labelBn: "মোট অ্যাপার্টমেন্ট", value: "16 Limited Units", valueBn: "১৬টি চমৎকার অ্যাপার্টমেন্ট" },
      { label: "Car Parking", labelBn: "গাড়ি পার্কিং", value: "Basement 1 Slot Each", valueBn: "বেসমেন্টে প্রতি ফ্ল্যাটে ১টি স্লট" }
    ],
    dwgUrl: "/uploads/Mollik P-1.dwg",
    dwgFilename: "Mollik P-1.dwg",
    pdfUrl: "/uploads/project 2 floor plan.pdf",
    pdfFilename: "project 2 floor plan.pdf"
  },
  {
    id: "mollik-grandeur",
    name: "Mollik City Tower - 5",
    nameBn: "মল্লিক সিটি টাওয়ার - ৫",
    location: "South Khan",
    locationBn: "দক্ষিণখান",
    type: "Residential",
    typeBn: "আবাসিক",
    size: "1300-2100 sqft",
    sizeBn: "১৩০০-২১০০ বর্গফুট",
    price: "৳60 Lac onwards",
    priceBn: "৳৬০ লক্ষ থেকে শুরু",
    status: "Upcoming",
    statusBn: "আসন্ন প্রকল্প",
    image: "/uploads/321cad5b-7fb9-4b85-93e7-66b1e5eb2673.JPG",
    description: "Mollik City Tower - 5 prioritizes modern ventilating design with ample natural air and sunshine in Uttarkhan, Dhaka. Excellent choice for safe family life with close walking proximity to local schools and shopping centers.",
    descriptionBn: "উত্তরখানে অবস্থিত মল্লিক সিটি টাওয়ার - ৫ সর্বাধিক প্রাকৃতিক আলো এবং বাতাস চলাচলের নকশায় তৈরি পরিকল্পিত আবাসন। এটি আপনার পরিবারের জন্য এক সুরক্ষিত এবং মনোরম আবাসের নিশ্চয়তা দেয়।",
    rajukApproved: true,
    earthquakeResistant: true,
    amenities: ["Multi-purpose Community Room", "Equipped Kids Playground", "Deep Tube Well Backup", "Fire escape staircase with smoke doors", "Driver's waiting quarters"],
    amenitiesBn: ["বহুমুখী কমিউনিটি হল রুম", "শরীরচর্চা ও শিশু বিনোদন পার্ক ব্যবস্থা", "ধোঁয়ানিরোধক ফায়ার এস্কেপ সিড়ি", "চালকদের অপেক্ষাগার"],
    specs: [
      { label: "Land Area", labelBn: "জমির পরিমাণ", value: "14 Katha", valueBn: "১৪ কাঠা" },
      { label: "Building Height", labelBn: "ভবনের উচ্চতা", value: "G + 15 Floors", valueBn: "জি + ১৫ তলা" },
      { label: "Total Apartments", labelBn: "মোট অ্যাপার্টমেন্ট", value: "30 Family Apartments", valueBn: "৩০টি ফ্যামিলি ফ্ল্যাট" },
      { label: "Car Parking", labelBn: "গাড়ি পার্কিং", value: "Secure Dual Level Garage", valueBn: "দ্বি-স্তরের সুরক্ষিত গ্যারেজ" }
    ],
    dwgUrl: "/uploads/প্রোজেক্ট ৫ আপডেট_1.dwg",
    dwgFilename: "প্রোজেক্ট ৫ আপডেট_1.dwg",
    pdfUrl: "/uploads/project 5 floor plan 3d.pdf",
    pdfFilename: "project 5 floor plan 3d.pdf"
  },
  {
    id: "mollik-splendour",
    name: "Mollik City VIP",
    nameBn: "মল্লিক সিটি VIP",
    location: "South Khan",
    locationBn: "দক্ষিণখান",
    type: "Penthouse",
    typeBn: "পেন্টহাউস / ডুপ্লেক্স",
    size: "2200-4500 sqft",
    sizeBn: "২২০০-৪৫০০ বর্গফুট",
    price: "৳2.5 Crore onwards",
    priceBn: "৳২.৫ কোটি থেকে শুরু",
    status: "Booking Open",
    statusBn: "বুকিং চলছে",
    image: "/uploads/486138b9-4e2d-43b0-b340-a2ae8f3b3d6c.JPG",
    description: "Mollik City VIP presents absolute luxury and exclusivity for prestigious buyers in Dakshinkhan. High density earthquake-resistant materials, spacious rooftop recreation deck, and elite private layouts defining majestic living.",
    descriptionBn: "ডাকশিনখান এলাকাতে আভিজাত্যের শেষ কথা নিয়ে দাঁড়িয়ে আছে মল্লিক সিটি VIP। শক্তিশালী ভূমিকম্প প্রতিরোধী নির্মাণ সামগ্রী এবং বিলাসবহুল ছাদবাগান আপনার লাইফস্টাইলকে করবে অনন্য ও দৃষ্টি নন্দন।",
    rajukApproved: true,
    earthquakeResistant: true,
    amenities: ["Smart Keyless Biometric Access", "Heated Hydrotherapy Jacuzzi Pool", "Multi-car Basement with dual EV Chargers", "Soundproof Cinema Auditorium", "State-of-the-art HVAC Central Climate Control", "24/7 Dedicated Diplomatic Guard Connection"],
    amenitiesBn: ["স্মার্ট বায়োমেট্রিক লক ও সিকিউরিটি", "হিটেড হাইড্রোথেরাপি জ্যাকুজি", "ইভি চার্জার্স বিশিষ্ট পার্কিং বেসমেন্ট", "শব্দ নিরোধক হোম থিয়েটার সুবিধা", "সেন্ট্রাল এসি ক্লাইমেট কন্ট্রোল", "বিশেষ ২৪/৭ নিরাপত্তা সংযোগ"],
    specs: [
      { label: "Land Area", labelBn: "জমির পরিমাণ", value: "16 Katha", valueBn: "১৬ কাঠা" },
      { label: "Building Height", labelBn: "ভবনের উচ্চতা", value: "G + 6 Floors", valueBn: "জি + ৬ তলা" },
      { label: "Total Apartments", labelBn: "মোট অ্যাপার্টমেন্ট", value: "10 Duplex Masterpieces", valueBn: "১০টি ডুপ্লেক্স মাস্টারপিস" },
      { label: "Car Parking", labelBn: "গাড়ি পার্কিং", value: "3 Assigned Slots Per Unit", valueBn: "প্রতি ইউনিটে ৩টি বরাদ্দকৃত পার্কিং" }
    ],
    dwgUrl: "/uploads/project 6 final.dwg",
    dwgFilename: "project 6 final.dwg",
    pdfUrl: "/uploads/project 6 floor plan.pdf",
    pdfFilename: "project 6 floor plan.pdf"
  },
  {
    id: "mollik-heritage",
    name: "Mollik City VIP - 7",
    nameBn: "মল্লিক সিটি VIP - ৭",
    location: "South Khan",
    locationBn: "দক্ষিণখান",
    type: "Residential",
    typeBn: "আবাসিক",
    size: "1500-2700 sqft",
    sizeBn: "১৫০০-২৭০০ বর্গফুট",
    price: "৳78 Lac onwards",
    priceBn: "৳৭৮ লক্ষ থেকে শুরু",
    status: "Ongoing",
    statusBn: "চলমান প্রকল্প",
    image: "/uploads/c2cdf210-72e7-437a-89a2-d779eaa5f27d.JPG",
    description: "Mollik City VIP - 7 brings vintage traditional styling blended with modern robust structural design to Uttarkhan, Dhaka. Earthquake compliant foundations, clay architectural details, and secure living for premium taste.",
    descriptionBn: "ঐতিহ্যবাহী নকশার সাথে আধুনিক মজবুত স্ট্রাকচারের অপরূপ সংমিশ্রণে উত্তরখানে নির্মিত হচ্ছে মল্লিক সিটি VIP - ৭। ভূমিকম্প সহনশীল শক্তিশালী ভিত্তি এবং চমৎকার লাল ইটের নান্দনিক ডিজাইনের এক নিরাপদ আবাসন।",
    rajukApproved: true,
    earthquakeResistant: true,
    amenities: ["Classic Community Courtyard", "Traditional Ground-floor Tea Lounge", "Rooftop Stargazing Green Deck", "Retractable Glass Canopy Over Atrium", "Large Emergency Water Reservoir System", "Fully-Equipped Fire Escape Protection System"],
    amenitiesBn: ["ঐতিহ্যবাহী কমিউনিটি কোর্ট ইয়ার্ড", "ক্লাসিক নিচতলা চা লাউঞ্জ", "দৃষ্টিনন্দন ছাদবাগান", "অ্যাট্রিয়াম কাঁচ ছাদ", "বিশাল ওয়াটার রিজার্ভার", "অত্যাধুনিক ফায়ার এস্কেপ নিরাপত্তা"],
    specs: [
      { label: "Land Area", labelBn: "জমির পরিমাণ", value: "11 Katha", valueBn: "১১ কাঠা" },
      { label: "Building Height", labelBn: "ভবনের উচ্চতা", value: "G + 10 Floors", valueBn: "জি + ১০ তলা" },
      { label: "Total Apartments", labelBn: "মোট অ্যাপার্টমেন্ট", value: "18 Vintage Residences", valueBn: "১৮টি প্রাচীন ঐতিহ্যবাহী ফ্ল্যাট" },
      { label: "Car Parking", labelBn: "গাড়ি পার্কিং", value: "1 Premium Slot per Apartment", valueBn: "প্রতি ফ্ল্যাটে ১টি প্রিমিয়াম স্লট" }
    ],
    dwgUrl: "/uploads/project 6 final.dwg",
    dwgFilename: "project 6 final.dwg",
    pdfUrl: "/uploads/project 6 floor plan.pdf",
    pdfFilename: "project 6 floor plan.pdf"
  },
  {
    id: "mollik-transmitter-a",
    name: "Mollik City 8.1",
    nameBn: "মল্লিক সিটি ৮.১",
    location: "Transmitter, Faydabad",
    locationBn: "ট্রান্সমিটার, ফায়দাবাদ",
    type: "Residential",
    typeBn: "আবাসিক",
    size: "1615 sqft",
    sizeBn: "১৬১৫ বর্গফুট",
    price: "৳18.7 Lac share",
    priceBn: "৳১৮.৭০ লক্ষ শেয়ার",
    status: "Ongoing",
    statusBn: "চলমান প্রকল্প",
    image: "/uploads/project 3.webp",
    description: "Mollik City 8.1 features an elegantly structured G+9 design with 3 Bed, 3 Bath, and 3 Verandas on a 6.73 Katha plot, located just 10 minutes east of Abdullapur Bus Stand.",
    descriptionBn: "৬.৭৩ কাঠা জমির ওপর নির্মিত ১০ তলা ভবনের ১৬১৫ বর্গফুটের বিলাসবহুল ফ্ল্যাট। আব্দুল্লাহপুর বাসস্ট্যান্ড থেকে পূর্বে ফায়দাবাদ পুলিশ ফাঁড়ি বাজারের কাছে।",
    rajukApproved: true,
    earthquakeResistant: true,
    amenities: ["Rooftop Garden", "CCTV Surveillance", "Fire Fighting System", "Emergency Generator", "1 Auto Elevator", "1 Wide Staircase"],
    amenitiesBn: ["দৃষ্টিনন্দন ছাদবাগান", "২৪/৭ সিসিটিভি ক্যামেরা", "ফায়ার ফাইটিং সিস্টেম", "জরুরি জেনারেটর ব্যাকআপ", "১টি অটোমেটেড লিফট", "১টি প্রশস্ত সিঁড়ি"],
    specs: [
      { label: "Land Area", labelBn: "জমির পরিমাণ", value: "6.73 Katha", valueBn: "৬.৭৩ কাঠা" },
      { label: "Building Height", labelBn: "ভবনের উচ্চতা", value: "G + 9 Floors", valueBn: "জি + ৯ তলা" },
      { label: "Total Apartments", labelBn: "মোট অ্যাপার্টমেন্ট", value: "27 Premium Units", valueBn: "২৭টি প্রিমিয়াম ইউনিট" },
      { label: "Car Parking", labelBn: "গাড়ি পার্কিং", value: "Available Ground Slot", valueBn: "সুরক্ষিত গ্রাউন্ড পার্কিং" }
    ],
    isLandShare: true,
    sharePrice: 1870000,
    installmentDue: 1057000,
    constructionCost: 2420000,
    minTotalInvestment: 4400000,
    maxTotalInvestment: 4620000
  },
  {
    id: "mollik-transmitter-b",
    name: "Mollik City 9.1",
    nameBn: "মল্লিক সিটি ৯.১",
    location: "Transmitter, Faydabad",
    locationBn: "ট্রান্সমিটার, ফায়দাবাদ",
    type: "Residential",
    typeBn: "রেডি ফ্ল্যাট",
    size: "1320 sqft",
    sizeBn: "১৩২০ বর্গফুট",
    price: "৳50.6 Lac",
    priceBn: "৳৫০.৬০ লক্ষ",
    status: "Few Units Left",
    statusBn: "রেডি ফ্ল্যাট",
    image: "/uploads/project 1.webp",
    description: "Mollik City 9.1 offers a fully ready South-West corner apartment on the 7th Floor (Unit B). High-quality construction on a 7.5 Katha plot with double lifts and BBQ zones.",
    descriptionBn: "৭.৫ কাঠা জমির ওপর সম্পূর্ণ রেডি ১০ তলা ভবনের ৭ম তলায় (ইউনিট-বি) দক্ষিণ-পশ্চিম কর্নারের ১৩২০ বর্গফুটের ফ্ল্যাট বিক্রয়।",
    rajukApproved: true,
    earthquakeResistant: true,
    amenities: ["Conference Room", "Rooftop BBQ Zone", "2 Auto Elevators", "Secure Garages", "Dual Standby Generator", "North-South Cross Ventilation"],
    amenitiesBn: ["কনফারেন্স হল রুম", "ছাদভিত্তিক বারবিকিউ জোন", "২টি অটোমেটেড লিফট", "সুরক্ষিত পার্কিং গ্যারেজ", "জরুরি জেনারেটর ব্যাকআপ", "উত্তর-দক্ষিণমুখী আলো-বাতাস"],
    specs: [
      { label: "Land Area", labelBn: "জমির পরিমাণ", value: "7.5 Katha", valueBn: "৭.৫ কাঠা" },
      { label: "Building Height", labelBn: "ভবনের উচ্চতা", value: "G + 9 Floors", valueBn: "জি + ৯ তলা" },
      { label: "Total Apartments", labelBn: "মোট অ্যাপার্টমেন্ট", value: "36 Spacious Homes", valueBn: "৩৬টি চমৎকার অ্যাপার্টমেন্ট" },
      { label: "Car Parking", labelBn: "গাড়ি পার্কিং", value: "Assigned Ground Slots", valueBn: "সুরক্ষিত পার্কিং স্লট" }
    ],
    isReadyFlat: true,
    flatPriceReady: 5060000
  },
  {
    id: "mollik-city-azampur",
    name: "Mollik City 10",
    nameBn: "মল্লিক সিটি ১০",
    location: "Uttara Azampur",
    locationBn: "উত্তরা আজমপুর",
    type: "Residential",
    typeBn: "আবাসিক",
    size: "1400-3200 sqft",
    sizeBn: "১৪০০-৩২০০ বর্গফুট",
    price: "৳12.1 Lac share",
    priceBn: "৳১২.১ লক্ষ শেয়ার",
    status: "Booking Open",
    statusBn: "বুকিং চলছে",
    image: "/uploads/Project 2.webp",
    description: "Mollik City 10 is an elite residential estate situated just 8-10 minutes from Azampur bus stand. Featuring an infinity pool, open gym, and party center next to a wide 60 ft primary road.",
    descriptionBn: "উত্তরা আজমপুর বাসস্ট্যান্ড থেকে মাত্র ৮-১০ মিনিট দূরত্বে মল্লিক সিটি। ইনফিনিটি সুইমিং পুল, ওপেন জিম এবং ৬০ ফিট চওড়া রাস্তার রাজকীয় আবাসন।",
    rajukApproved: true,
    earthquakeResistant: true,
    amenities: ["Infinity Swimming Pool", "Open-air Rooftop Gym", "Executive Party Center", "24/7 Security Concierge", "Automated High-speed Lifts", "Integrated EV Charging Port"],
    amenitiesBn: ["ইনফিনিটি সুইমিং পুল", "ছাদভিত্তিক ওপেন জিম", "এক্সিকিউটিভ পার্টি সেন্টার", "২৪/৭ সিকিউরিটি কনসিয়ার্জ", "হাই-স্পিড অটোমেটেড লিফট", "ইভি চার্জারযুক্ত পার্কিং"],
    specs: [
      { label: "Land Area", labelBn: "জমির পরিমাণ", value: "18 Katha", valueBn: "১৮ কাঠা" },
      { label: "Building Height", labelBn: "ভবনের উচ্চতা", value: "G + 14 Floors", valueBn: "জি + ১৪ তলা" },
      { label: "Total Apartments", labelBn: "মোট অ্যাপার্টমেন্ট", value: "45 Premium Units", valueBn: "৪৫টি প্রিমিয়াম ইউনিট" },
      { label: "Car Parking", labelBn: "গাড়ি পার্কিং", value: "Basement Parking Bays", valueBn: "বেসমেন্ট পার্কিং স্লট" }
    ],
    isLandShare: true,
    sharePrice: 1210000,
    installmentDue: 0,
    constructionCost: 2420000,
    minTotalInvestment: 3630000,
    maxTotalInvestment: 3850000
  },
  {
    id: "mollik-transmitter-d",
    name: "Mollik Transmitter Avenue",
    nameBn: "মল্লিক ট্রান্সমিটার এভিনিউ",
    location: "Transmitter, Faydabad",
    locationBn: "ট্রান্সমিটার, ফায়দাবাদ",
    type: "Residential",
    typeBn: "আবাসিক",
    size: "1350 sqft",
    sizeBn: "১৩৫০ বর্গফুট",
    price: "৳16.5 Lac share",
    priceBn: "৳১৬.৫০ লক্ষ শেয়ার",
    status: "Ongoing",
    statusBn: "চলমান প্রকল্প",
    image: "/uploads/project 8.webp",
    description: "Mollik Transmitter Avenue is a high-yield residential project on a 12 Katha plot. Offering G+9 storeys with 6 units per floor, dual elevators, and full seismic deflecting BNBC layout.",
    descriptionBn: "১২ কাঠা জমির ওপর জি+৯ তলাবিশিষ্ট কন্সট্রাকশন প্রজেক্ট। বর্তমানে ৯ম তলার ছাদ ঢালাইয়ের কাজ চলমান। প্রতি তলায় ৬টি করে চমৎকার অ্যাপার্টমেন্ট।",
    rajukApproved: true,
    earthquakeResistant: true,
    amenities: ["Dual Smart Elevators", "Wide Double Staircase", "Fire escape staircase with smoke doors", "Standby Power Generator", "CCTV & Security Shield", "Rooftop Observation Green Deck"],
    amenitiesBn: ["২টি স্মার্ট এলিভেটর", "২টি সুপ্রশস্ত সিঁড়ি", "ফায়ার সেফটি ও ধোঁয়ানিরোধক দরজা", "জরুরি বিদ্যুৎ জেনারেটর", "২৪ ঘণ্টা সিসিটিভি ক্যামেরা", "সবুজ ছাদবাগান লাউঞ্জ"],
    specs: [
      { label: "Land Area", labelBn: "জমির পরিমাণ", value: "12 Katha", valueBn: "১২ কাঠা" },
      { label: "Building Height", labelBn: "ভবনের উচ্চতা", value: "G + 9 Floors", valueBn: "জি + ৯ তলা" },
      { label: "Total Apartments", labelBn: "মোট অ্যাপার্টমেন্ট", value: "54 Family Apartments", valueBn: "৫৪টি ফ্যামিলি ফ্ল্যাট" },
      { label: "Car Parking", labelBn: "গাড়ি পার্কিং", value: "1 Secured Space per Unit", valueBn: "প্রতি ফ্ল্যাটে ১টি সুরক্ষিত পার্কিং" }
    ],
    isLandShare: true,
    sharePrice: 1650000,
    installmentDue: 0,
    constructionCost: 2420000,
    minTotalInvestment: 3960000,
    maxTotalInvestment: 4180000
  },
  {
    id: "mollik-city-plots",
    name: "Mollik City Ready Plots",
    nameBn: "মল্লিক সিটি রেডি প্লট",
    location: "Uttarkhan Primary School",
    locationBn: "উত্তরখান প্রাইমারি স্কুল",
    type: "Residential",
    typeBn: "রেডি প্লট",
    size: "9 Katha each",
    sizeBn: "৯ কাঠা করে ২টি প্লট",
    price: "৳85 Lac per Katha",
    priceBn: "৳৮৫ লক্ষ প্রতি কাঠা",
    status: "Few Units Left",
    statusBn: "রেডি প্লট",
    image: "/uploads/project 3.webp",
    description: "Two premium 9 Katha residential plots next to Uttarkhan Primary School near Mazar Chowrasta. Features 3-side open road access and ready legal mutation documents.",
    descriptionBn: "উত্তরখান প্রাইমারি স্কুলের পাশে ৯ কাঠা করে ২টি রেডি প্লট বিক্রয় করা হবে। ৩ দিক খোলা রাস্তা এবং হালনাগাদ কাগজপত্রসহ সম্পূর্ণ রেডি প্লট।",
    rajukApproved: true,
    earthquakeResistant: false,
    amenities: ["3-Side Open Road Access", "Updated Legal Deed Records", "Immediate Boundary Wall", "Near Mosque & School", "Close to Express Highway", "Electricity/Gas Ready Connection"],
    amenitiesBn: ["৩ দিক খোলা রাস্তা", "হালনাগাদ রেজিস্ট্রি ও পর্চা", "সীমানা প্রাচীর দিয়ে ঘেরা", "মসজিদ ও স্কুলের নিকটে", "এক্সপ্রেসওয়ের খুব কাছে", "বিদ্যুৎ ও গ্যাস সংযোগ উপযোগী"],
    specs: [
      { label: "Land Area", labelBn: "জমির পরিমাণ", value: "9 Katha", valueBn: "৯ কাঠা" },
      { label: "Total Plots Available", labelBn: "মোট প্লট সংখ্যা", value: "2 Ready Plots", valueBn: "২টি রেডি প্লট" },
      { label: "Road Access Width", labelBn: "রাস্তার চওড়া সাইজ", value: "20 Ft and 15 Ft Roads", valueBn: "২০ ফিট এবং ১৫ ফিট রাস্তা" },
      { label: "Zoning Permission", labelBn: "জোনিং অনুমতি", value: "Residential Highrise Permitted", valueBn: "আবাসিক বহুতল ভবন উপযোগী" }
    ],
    isReadyPlot: true,
    pricePerKatha: 8500000
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    name: "Mohammad Rahman",
    nameBn: "মোহাম্মদ রহমান",
    location: "Gulshan",
    locationBn: "গুলশান",
    rating: 5,
    comment: "Mollik Builders delivered our dream home on time with exceptional structural finishing and transparent communication. Highly recommended!",
    commentBn: "মল্লিক বিল্ডার্স সময়মতো আমাদের স্বপ্নের বাড়ি হস্তান্তর করেছে। চমৎকার কোয়ালিটি ও পরিষ্কার যোগাযোগের জন্য আমি অত্যন্ত সন্তুষ্ট।",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150"
  },
  {
    name: "Dr. Samia Chowdhury",
    nameBn: "ডাঃ সামিয়া চৌধুরী",
    location: "Uttara",
    locationBn: "উত্তরা",
    rating: 5,
    comment: "The eco-friendly layout of Mollik Garden is exceptional. The vertical greens and rainwater management show true future proofing.",
    commentBn: "মল্লিক গার্ডেনের পরিবেশবান্ধব ডিজাইন অসাধারণ। ভার্টিক্যাল গার্ডেন ও ওয়াটার প্ল্যান আধুনিক প্রিমিয়াম স্থাপত্যের পরিচয় বহন করে।",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=150"
  },
  {
    name: "Afridi Ahmed",
    nameBn: "আফ্রিদি আহমেদ",
    location: "Dhanmondi",
    locationBn: "ধানমন্ডি",
    rating: 5,
    comment: "Transparent dealing, no hidden charges, and continuous photo updates during construction keep landowners relaxed throughout the project.",
    commentBn: "স্বচ্ছ চুক্তি, কোনো লুকানো কস্ট নেই এবং কনস্ট্রাকশনের সময় প্রতিনিয়ত ফোটো আপডেট জমির মালিকদের শতভাগ দুশ্চিন্তামুক্ত রাখে।",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150"
  }
];

export const ARTICLES: BlogArticle[] = [
  {
    id: "tip-real-estate",
    title: "Real Estate Investment Tips in Bangladesh",
    titleBn: "বাংলাদেশে রিয়েল এস্টেট বিনিয়োগের গুরুত্ব ও টিপস",
    category: "Investment",
    categoryBn: "বিনিয়োগ",
    date: "June 05, 2026",
    dateBn: "০৫ জুন, ২০২৬",
    image: "/uploads/project 3.webp",
    readTime: "5 mins read",
    readTimeBn: "৫ মিনিট পাঠ",
    summary: "Dhaka's property landscape is evolving rapidly. Discover key high-return areas, RAJUK compliance checklists, and property valuation methods.",
    summaryBn: "ঢাকার প্রপার্টি মার্কেট দ্রুত পরিবর্তন হচ্ছে। উচ্চ আয়ের এলাকা, রাজুক আইন এবং প্রপার্টি যাচাই করার সঠিক উপায়গুলো জানুন।"
  },
  {
    id: "buyer-guide",
    title: "Comprehensive Home Buying Guide: Dhaka",
    titleBn: "অ্যাপার্টমেন্ট কেনার পূর্ণাঙ্গ গাইডবুক: ঢাকা",
    category: "Guide",
    categoryBn: "গাইডবুক",
    date: "May 28, 2026",
    dateBn: "২৮ মে, ২০২৬",
    image: "/uploads/project 1.webp",
    readTime: "7 mins read",
    readTimeBn: "৭ মিনিট পাঠ",
    summary: "From legal verification of mutation parcha to planning your bank downpayment installments in BDT, here is step-by-step guidance for first-time buyers.",
    summaryBn: "মিউটেশন পর্চা যাচাই থেকে শুরু করে ব্যাংকিং কিস্তি প্ল্যানিং করা পর্যন্ত প্রথম ক্রেতাদের জন্য ধাপে ধাপে নির্দেশনা।"
  },
  {
    id: "interior-trends",
    title: "Premium Minimalist Interior Design Trends",
    titleBn: "প্রিমিয়াম মিনিমালিস্ট ইন্টেরিয়র ডিজাইন ট্রেন্ডস",
    category: "Design",
    categoryBn: "ডিজাইন",
    date: "May 15, 2026",
    dateBn: "১৫ মে, ২০২৬",
    image: "/uploads/Project 2.webp",
    readTime: "4 mins read",
    readTimeBn: "৪ মিনিট পাঠ",
    summary: "How to maximize light in tight city flats. Learn about wood pairings, hidden panel lighting, and natural stone features.",
    summaryBn: "শহরের ফ্ল্যাটে কীভাবে পর্যাপ্ত সূর্যের আলো নিশ্চিত করা সম্ভব। কাঠ, ইন্টিগ্রেটেড প্যানেল লাইটিং এবং প্রাকৃতিক পাথরের চমৎকার ব্যবহার আলোচনা।"
  }
];

export const CAREERS_LIST: CareerJob[] = [
  {
    id: "structural-eng",
    title: "Senior Structural Design Engineer",
    titleBn: "সিনিয়র স্ট্রাকচারাল ডিজাইন ইঞ্জিনিয়ার",
    department: "Engineering & Design",
    departmentBn: "ইঞ্জিনিয়ারিং ও ডিজাইন",
    location: "Corporate HQ, South Khan",
    type: "Full-Time",
    typeBn: "ফুল-টাইম",
    experience: "8+ Years",
    experienceBn: "৮+ বছর",
    deadline: "July 10, 2026"
  },
  {
    id: "relation-mgr",
    title: "Premium Client Relations Manager",
    titleBn: "প্রিমিয়াম ক্লায়েন্ট রিলেশন ম্যানেজার",
    department: "Sales & Advisory",
    departmentBn: "সেলস অ্যান্ড কাস্টমার রিলেশন",
    location: "Corporate HQ, South Khan",
    type: "Full-Time",
    typeBn: "ফুল-টাইম",
    experience: "4+ Years",
    experienceBn: "৪+ বছর",
    deadline: "June 30, 2026"
  },
  {
    id: "site-supervisor",
    title: "Project Site Supervisor",
    titleBn: "প্রকল্প সাইট সুপারভাইজার",
    department: "Construction Management",
    departmentBn: "নির্মাণ ও প্রকৌশল",
    location: "Gulshan / Banani Sites",
    type: "Full-Time",
    typeBn: "ফুল-টাইম",
    experience: "5+ Years",
    experienceBn: "৫+ বছর",
    deadline: "July 05, 2026"
  }
];

export const FAQS_LIST: FAQ[] = [
  {
    question: "Are all Mollik Builders projects RAJUK approved?",
    questionBn: "মল্লিক বিল্ডার্সের সব প্রজেক্ট কি রাজুক (RAJUK) অনুমোদিত?",
    answer: "Yes, 100% of our residential and commercial builds are strictly RAJUK approved. We strictly abide by the Dhaka Metropolitan Building Construction Rules (ঢাকা মহানগর ইমারত নির্মাণ বিধিমালা) and secure all relevant clearance certificates (structural layout, fire safety, environmental clearance) before opening bookings.",
    answerBn: "হ্যাঁ, আমাদের সব আবাসিক ও বাণিজ্যিক প্রজেক্ট শতভাগ রাজুক অনুমোদিত। আমরা ঢাকা মহানগর ইমারত নির্মাণ বিধিমালা কঠোরভাবে মেনে চলি এবং বুকিং শুরু করার আগেই কাঠামোগত নিরাপত্তা, ফায়ার সেফটি ও পরিবেশগত ছাড়পত্র সংগ্রহ করি।"
  },
  {
    question: "What structural measures ensure earthquake protection?",
    questionBn: "ভূমিকম্প থেকে সুরক্ষায় কী ধরনের কাঠামোগত ব্যবস্থা নেওয়া হয়?",
    answer: "Every structure designed by Mollik Builders strictly complies with the Bangladesh National Building Code (BNBC). We utilize premium 72.5 grade steel, micro-concrete piles, and expert wind-load modeling. The foundations are analyzed to safely isolate and resist seismic occurrences up to Richter Magnitude 7.5.",
    answerBn: "মল্লিক বিল্ডার্সের তৈরি প্রতিটি কাঠামো বাংলাদেশ ন্যাশনাল বিল্ডিং কোড (BNBC) শতভাগ অনুসরণ করে। আমরা ৭২.৫ গ্রেড স্টিল রড, মাইক্রো-কংক্রিট পাইল এবং অত্যাধুনিক উইন্ড-লোড মডেলিং ব্যবহার করি। সাড়ে ৭ মাত্রার শক্তিশালী ভূমিকম্পেও ভবন যাতে নিরাপদ থাকে আমরা তা নিশ্চিত করি।"
  },
  {
    question: "Do you offer flexible installment options for buyers?",
    questionBn: "আপনাদের কি প্রপার্টি ক্রয়ের জন্য সহজ কিস্তির সুযোগ রয়েছে?",
    answer: "Absolutely. We offer interest-free construction milestone-linked payment schemes lasting up to 36 months. Downpayment is typically 30%, followed by customized quarterly or monthly installments according to structural handovers. We also have partnerships with leading commercial banks for quick home-loan processing.",
    answerBn: "অবশ্যই। আমরা ৩৬ মাস পর্যন্ত নির্মাণকাজের অগ্রগতির সাথে সমন্বয় রেখে সুদ-মুক্ত কিস্তির সুবিধা প্রদান করি। সাধারণত ডাউনপেমেন্ট ৩০% হয়, এবং বাকি পেমেন্ট মাসিক বা ত্রৈমাসিক কিস্তিতে দেওয়া যায়। এছাড়া দ্রুত গৃহ ঋণ প্রসেস করার জন্য শীর্ষস্থানীয় ব্যাংকগুলোর সাথে আমাদের চুক্তি আছে।"
  },
  {
    question: "How do landowners benefit from a joint venture with Mollik Builders?",
    questionBn: "জমির মালিকরা মল্লিক বিল্ডার্সের সাথে অংশীদারিত্ব করলে কী কী সুবিধা পাবেন?",
    answer: "Landowners earn maximum financial and structural yields through fair ratios, guaranteed premium grade building materials, state-of-the-art earthquake compliance, complete and transparent documentation, timely handovers with delayed penalty insurance clauses, and beautiful architectural benchmarks that elevate overall asset value.",
    answerBn: "জমির মালিক সঠিক লভ্যাংশ, আন্তর্জাতিক মানের নির্মাণ কন্সট্রাকশন সামগ্রী, ভূমিকম্প প্রতিরোধী নকশা, শতভাগ স্বচ্ছ ডক্যুমেন্টশন, এবং সময়মতো ডেডলাইন নিশ্চিত চুক্তিসহ এক আধুনিক প্রিমিয়াম স্থাপত্যের অংশীদার হয়ে নিজের সম্পত্তির সর্বোচ্চ মূল্য লাভ করেন।"
  }
];
